### ISSUE TITLE
Missing style.css in npm

### ISSUE THREAD

**Issue by msaari** [pablovila/react-text-datepicker#5]
Hi,

I installed react-text-datepicker from npm. When I added the component to my project, I got an error message:

`Module not found: Can't resolve './style.css' in '/../node_modules/react-text-datepicker/es'`

Looks like the style.css file is missing from the npm package. Once I got it from GitHub and put it in the /es directory, everything works fine.

**Comment by pablovila** [comment]
Hi! Thanks for trying out this lib. I have checked it and you're right. I have updated the lib to 1.0.4 solving this issue.
